// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchTrackerFile(arg1:string):Promise<void>;

export function GetRequiredContent():Promise<Array<main.TunnelTracerContent>>;

export function ListenToPeers(arg1:string):Promise<void>;
