// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchTrackerFile(arg1:string):Promise<void>;

export function ListenToPeers(arg1:string):Promise<void>;
