// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnnounceCurrentFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnnounceCurrentFile'](arg1, arg2, arg3, arg4);
}

export function CheckIfAllSegmentAreAvaliable(arg1) {
  return window['go']['main']['App']['CheckIfAllSegmentAreAvaliable'](arg1);
}

export function FetchTrackerFile(arg1) {
  return window['go']['main']['App']['FetchTrackerFile'](arg1);
}

export function GetRequiredContent() {
  return window['go']['main']['App']['GetRequiredContent']();
}

export function ListenToPeers(arg1) {
  return window['go']['main']['App']['ListenToPeers'](arg1);
}

export function MakeOriginaleFile(arg1) {
  return window['go']['main']['App']['MakeOriginaleFile'](arg1);
}

export function MakeRequiredFile() {
  return window['go']['main']['App']['MakeRequiredFile']();
}

export function RequestRequiredSegments(arg1) {
  return window['go']['main']['App']['RequestRequiredSegments'](arg1);
}
