// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnnounceCurrentFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckIfAllSegmentAreAvaliable(arg1:Array<main.SegmentFileAddress>):Promise<Array<main.SegmentFileAddress>>;

export function FetchTrackerFile(arg1:string):Promise<void>;

export function GetRequiredContent():Promise<Array<main.TunnelTracerContent>>;

export function ListenToPeers(arg1:string):Promise<void>;

export function MakeOriginaleFile(arg1:string):Promise<void>;

export function MakeRequiredFile():Promise<void>;

export function RequestRequiredSegments(arg1:string):Promise<void>;
