// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchTrackerFile(arg1) {
  return window['go']['main']['App']['FetchTrackerFile'](arg1);
}

export function ListenToPeers(arg1) {
  return window['go']['main']['App']['ListenToPeers'](arg1);
}
